'use client'

import { useEffect, useState } from 'react'

export default function MappingsPage(){
 const [forms,setForms]=useState<any[]>([]),[fields,setFields]=useState<any[]>([]),[mappings,setMappings]=useState<any[]>([]);const [formId,setFormId]=useState('');const [formFields,setFormFields]=useState<any[]>([]);const [source,setSource]=useState('');const [target,setTarget]=useState('');const [message,setMessage]=useState('')
 async function load(){const r=await fetch('/api/mappings',{cache:'no-store'});const d=await r.json();if(r.status===401)return window.location.href='/login';if(!r.ok)return setMessage(d.error);setForms(d.forms||[]);setFields(d.fields||[]);setMappings(d.mappings||[]);if(!formId&&d.forms?.[0])setFormId(d.forms[0].id)}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(!formId)return;fetch(`/api/forms/${formId}`,{cache:'no-store'}).then(r=>r.json()).then(d=>setFormFields(d.fields||[]))},[formId])
 async function add(){const r=await fetch('/api/mappings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({form_id:formId,form_field_key:source,target_key:target})});const d=await r.json();setMessage(r.ok?'Mapping saved.':d.error);if(r.ok){setSource('');await load()}}
 async function remove(id:string){await fetch(`/api/mappings?id=${id}`,{method:'DELETE'});await load()}
 return <div className="shell"><aside className="sidebar"><div className="brand">ACP CRM</div><nav className="nav"><a href="/">Dashboard</a><a href="/customers">Customers</a><a href="/admin/forms">Forms</a><a className="active" href="/admin/mappings">Mappings</a><a href="/admin/automations">Automations</a></nav></aside><main className="main"><div className="top"><div><div className="eyebrow">Admin</div><h1 className="title">Field Mappings</h1><p className="muted">Connect any form field to a customer field for automation.</p></div></div><section className="card"><div className="mapping-grid"><label>Form<select value={formId} onChange={e=>setFormId(e.target.value)}>{forms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Form field<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Select…</option>{formFields.map(f=><option key={f.field_key} value={f.field_key}>{f.label} ({f.field_key})</option>)}</select></label><label>Customer field<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Select…</option>{fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><button className="btn" onClick={add} disabled={!formId||!source||!target}>Add mapping</button></div></section><section className="card section"><h2>Active mappings</h2>{mappings.length===0?<p className="muted">No mappings yet.</p>:<div className="list">{mappings.map(m=><div className="row" key={m.id}><span><strong>{m.form_field_key}</strong> → <strong>{m.target_key}</strong><small>{forms.find(f=>f.id===m.form_id)?.name||'Form'}</small></span><button className="btn danger" onClick={()=>remove(m.id)}>Remove</button></div>)}</div>}</section>{message&&<div className="notice">{message}</div>}</main></div>
}
