'use client'

import { useEffect, useState } from 'react'

export default function FormRunner({params}:{params:Promise<{id:string}>}){const [id,setId]=useState(''),[form,setForm]=useState<any>(null),[fields,setFields]=useState<any[]>([]),[answers,setAnswers]=useState<Record<string,any>>({}),[message,setMessage]=useState(''),[saving,setSaving]=useState(false)
 useEffect(()=>{params.then(p=>setId(p.id))},[params]);useEffect(()=>{if(!id)return;fetch(`/api/forms/${id}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)return setMessage(d.error||'Unable to load form');setForm(d.form);setFields(d.fields||[])})},[id])
 function visible(f:any){const rule=f.visibility_rule||{};if(!rule.field_key)return true;const v=answers[rule.field_key];return rule.operator==='not_equals'?v!==rule.value:v===rule.value}
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage('');const r=await fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({form_id:id,answers})});const d=await r.json();setSaving(false);if(!r.ok)return setMessage(d.error||'Submission failed');setMessage('Submitted successfully. Customer record and automations have been updated.');setAnswers({})}
 function control(f:any){const value=answers[f.field_key]??'';const set=(v:any)=>setAnswers(a=>({...a,[f.field_key]:v}));if(f.field_type==='long_text')return <textarea value={value} onChange={e=>set(e.target.value)}/>;if(f.field_type==='checkbox')return <input type="checkbox" checked={Boolean(value)} onChange={e=>set(e.target.checked)}/>;if(['select','radio'].includes(f.field_type))return <select value={value} onChange={e=>set(e.target.value)}><option value="">Select…</option>{(f.config?.options||[]).map((o:string)=><option key={o}>{o}</option>)}</select>;if(f.field_type==='multi_select')return <select multiple value={Array.isArray(value)?value:[]} onChange={e=>set(Array.from(e.target.selectedOptions).map(o=>o.value))}>{(f.config?.options||[]).map((o:string)=><option key={o}>{o}</option>)}</select>;return <input type={f.field_type==='number'?'number':f.field_type==='date'?'date':f.field_type==='email'?'email':f.field_type==='phone'?'tel':'text'} value={value} onChange={e=>set(e.target.value)}/>}
 if(!form)return <main className="main"><section className="card">{message||'Loading form…'}</section></main>
 return <main className="main"><div className="top"><div><div className="eyebrow">Form</div><h1 className="title">{form.name}</h1><p className="muted">{form.description}</p></div><a className="btn secondary" href="/">CRM</a></div><form className="card section form-stack" onSubmit={submit}>{fields.filter(visible).map(f=><label key={f.id}>{f.label}{f.required?' *':''}{control(f)}</label>)}<button className="btn" disabled={saving}>{saving?'Submitting…':'Submit form'}</button>{message&&<div className="notice">{message}</div>}</form></main>
}
