'use client'

import { useEffect, useMemo, useState } from 'react'

type Role = { id:string; name:string; description:string|null; is_system:boolean; is_owner:boolean }
type Permission = { id:string; key:string; name:string; description:string|null; module:string }
type Member = { id:string; user_id:string; role_id:string|null; role:string; created_at:string }

export default function RolesPage(){
  const [roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[links,setLinks]=useState<any[]>([]),[members,setMembers]=useState<Member[]>([]),[editing,setEditing]=useState<any>(null),[message,setMessage]=useState(''),[newName,setNewName]=useState('')
  async function load(){const r=await fetch('/api/roles',{cache:'no-store'});if(r.status===401)return window.location.href='/login';const d=await r.json();if(!r.ok)return setMessage(d.error||'Unable to load roles');setRoles(d.roles||[]);setPermissions(d.permissions||[]);setLinks(d.rolePermissions||[]);setMembers(d.members||[])}
  useEffect(()=>{load()},[])
  const grouped=useMemo(()=>permissions.reduce((a,p)=>{(a[p.module]??=[]).push(p);return a},{} as Record<string,Permission[]>),[permissions])
  function permsFor(id:string){return links.filter(x=>x.role_id===id).map(x=>x.permission_id)}
  function edit(role:Role){setEditing({...role,permission_ids:permsFor(role.id)})}
  function togglePermission(id:string){setEditing((e:any)=>({...e,permission_ids:e.permission_ids.includes(id)?e.permission_ids.filter((x:string)=>x!==id):[...e.permission_ids,id]}))}
  async function save(){if(!editing)return;const r=await fetch('/api/roles',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editing.id,name:editing.name,description:editing.description,permission_ids:editing.permission_ids})});const d=await r.json();if(!r.ok)return setMessage(d.error||'Save failed');setMessage('Role saved.');setEditing(null);load()}
  async function create(){const name=newName.trim();if(!name)return;const r=await fetch('/api/roles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,permission_ids:[]})});const d=await r.json();if(!r.ok)return setMessage(d.error||'Could not create role');setNewName('');setMessage('Role created.');await load();edit(d.role)}
  async function remove(id:string){if(!confirm('Delete this role?'))return;const r=await fetch('/api/roles?id='+id,{method:'DELETE'});const d=await r.json();if(!r.ok)return setMessage(d.error||'Delete failed');setMessage('Role deleted.');load()}
  async function assign(memberId:string,roleId:string){const r=await fetch('/api/members',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({member_id:memberId,role_id:roleId})});const d=await r.json();if(!r.ok)return setMessage(d.error||'Assignment failed');setMessage('Role assigned.');load()}
  return <div className="shell"><aside className="sidebar"><div className="brand">ACP CRM</div><nav className="nav"><a href="/">Dashboard</a><a href="/customers">Customers</a><a href="/admin/forms">Forms</a><a href="/admin/mappings">Mappings</a><a href="/admin/automations">Automations</a><a className="active" href="/admin/roles">Team & Roles</a><a href="/tasks">Tasks</a></nav></aside><main className="main">
    <div className="top"><div><div className="eyebrow">Administration</div><h1 className="title">Team & Roles</h1><p className="muted">Create your own roles and decide exactly what each role can access.</p></div></div>
    <section className="card section"><div className="section-head"><h2>Roles</h2><div className="toolbar-actions"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="New role name"/><button className="btn" onClick={create}>＋ Create role</button></div></div><div className="list">{roles.map(r=><div className="row" key={r.id}><span><strong>{r.name}{r.is_owner?' · Protected':''}</strong><small>{r.description||'Custom role'}{r.is_system?' · System default':''}</small></span><span className="toolbar-actions"><button className="btn secondary" onClick={()=>edit(r)}>Edit</button>{!r.is_owner&&<button className="btn danger" onClick={()=>remove(r.id)}>Delete</button>}</span></div>)}</div></section>
    {editing&&<section className="card section"><div className="section-head"><div><h2>Edit role</h2><p className="muted">Changes apply to everyone assigned this role.</p></div><button className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button></div><div className="form-stack"><label>Role name<input value={editing.name} disabled={editing.is_owner} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Description<input value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><h3>Permissions</h3>{Object.entries(grouped).map(([module,ps])=><div key={module}><h3>{module}</h3><div className="grid">{ps.map(p=><label className="card" key={p.id}><span className="check"><input type="checkbox" checked={editing.is_owner||editing.permission_ids.includes(p.id)} disabled={editing.is_owner} onChange={()=>togglePermission(p.id)}/><strong>{p.name}</strong></span><small>{p.description}</small></label>)}</div></div>)}{!editing.is_owner&&<button className="btn" onClick={save}>Save role</button>}</div></section>}
    <section className="card section"><div className="section-head"><div><h2>Staff assignments</h2><p className="muted">Assign a role to each organisation member.</p></div></div><div className="list">{members.map(m=><div className="row" key={m.id}><span><strong>{m.user_id}</strong><small>Member since {new Date(m.created_at).toLocaleDateString('en-AU')}</small></span><select value={m.role_id||''} onChange={e=>assign(m.id,e.target.value)}><option value="" disabled>Select role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>)}</div>{members.length===0&&<p className="muted">No staff members found.</p>}</section>
    {message&&<div className="notice">{message}</div>}
  </main></div>
}
